version: '3'

services:
  expecter:
    build:
      context: .
      x-bake:
        tags:
          - ghcr.io/matti/expecter:${GITHUB_SHA}
        platforms:
          - linux/amd64
          - linux/arm64
